name: Run Load Test

on:
  workflow_dispatch:

jobs:
  run-loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and run tests
        run: docker-compose up --build --abort-on-container-exit

      - name: Upload NBomber report
        uses: actions/upload-artifact@v4
        with:
          name: LoadTestReport
          path: ./loadtest-reports/
